In [1]:
import pandas as pd

In [3]:
iphone_df = pd.read_csv('data/iphone.csv', index_col = 0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [6]:
iphone_df.loc['iPhone 8', '메모리'] = '2.5GB'

In [7]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [8]:
iphone_df.loc['iPhone 8', '출시 버전'] = 'ios 10.3'

In [9]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  ios 10.3      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [10]:
iphone_df.loc['iPhone 8']

출시일        2017-09-22
디스플레이             4.7
메모리             2.5GB
출시 버전        ios 10.3
Face ID            No
Name: iPhone 8, dtype: object

In [11]:
iphone_df.loc['iPhone 8'] = ['2016-07-25', '4.7', '2GB', 'ios 11.0', 'No']

In [12]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0      No
iPhone 8       2016-07-25   4.7  2GB  ios 11.0      No
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes

In [13]:
iphone_df['디스플레이']

iPhone 7         4.7
iPhone 7 Plus    5.5
iPhone 8         4.7
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: object

In [14]:
iphone_df['디스플레이'] =['4.7 in', '5.5 in', '4.7 in', '5.5 in', '5.8 in' , '5.8 in', '6.5 in']

In [15]:
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.7 in  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0      No
iPhone 8       2016-07-25  4.7 in  2GB  ios 11.0      No
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0      No
iPhone X       2017-11-03  5.8 in  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  6.5 in  4GB  iOS 12.0     Yes

In [16]:
iphone_df['Face ID']

iPhone 7          No
iPhone 7 Plus     No
iPhone 8          No
iPhone 8 Plus     No
iPhone X         Yes
iPhone XS        Yes
iPhone XS Max    Yes
Name: Face ID, dtype: object

In [17]:
iphone_df['Face ID'] = 'Yes'

In [18]:
iphone_df

                      출시일   디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.7 in  2GB  iOS 10.0     Yes
iPhone 7 Plus  2016-09-16  5.5 in  3GB  iOS 10.0     Yes
iPhone 8       2016-07-25  4.7 in  2GB  ios 11.0     Yes
iPhone 8 Plus  2017-09-22  5.5 in  3GB  iOS 11.0     Yes
iPhone X       2017-11-03  5.8 in  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8 in  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  6.5 in  4GB  iOS 12.0     Yes

In [19]:
iphone_df[['디스플레이', 'Face ID']] = 'X'
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     X  2GB  iOS 10.0       X
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       X
iPhone 8       2016-07-25     X  2GB  ios 11.0       X
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       X
iPhone X       2017-11-03     X  3GB  iOS 11.1       X
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X

In [20]:
iphone_df.loc[['iPhone 7', 'iPhone X']] = 'O'

In [21]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                O     O    O         O       O
iPhone 7 Plus  2016-09-16     X  3GB  iOS 10.0       X
iPhone 8       2016-07-25     X  2GB  ios 11.0       X
iPhone 8 Plus  2017-09-22     X  3GB  iOS 11.0       X
iPhone X                O     O    O         O       O
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X

In [23]:
iphone_df.loc['iPhone 7' : 'iPhone X'] = 'O'

In [24]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7                O     O    O         O       O
iPhone 7 Plus           O     O    O         O       O
iPhone 8                O     O    O         O       O
iPhone 8 Plus           O     O    O         O       O
iPhone X                O     O    O         O       O
iPhone XS      2018-09-21     X  4GB  iOS 12.0       X
iPhone XS Max  2018-09-21     X  4GB  iOS 12.0       X